Algoritmo "exercicio_fora_da_lista"
//turmac_60
//turmad_20
Var

quantidade,taxa, porcentagem, resultado: real
rep_turmaC,rep_turmaD,turmaC, turmaD: inteiro


Inicio
 escreval("Quantidade de alunos na turmaC: ")
  leia(Quantidade)

  escreval(" Taxa de alunos rep turmaC: ")
  leia(taxa)

  porcentagem <- (Quantidade ^ Taxa ) / 100

  escreval("A porcentagem é:  ", porcentagem, "%")

Fimalgoritmo